# https://taskfile.dev

version: '3'

vars:
  EXAMPLES_DIR: examples

includes:
  workspace: ./tasks/workspace
  sops: ./tasks/sops
  device: ./tasks/device
  docker: tasks/docker
  vhs: tasks/vhs
  talos: tasks/talos

tasks:
  how-to-examples:
    silent: true
    cmds:
      - echo "Welcome to Workspace Documentation!"
      - echo "Available examples:"
      - |
        for dir in {{.EXAMPLES_DIR}}/*/; do
          if [ -f "${dir}Taskfile.yml" ]; then
            echo "- $(basename ${dir%/})"
          fi
        done
      - echo ""
      - echo "To work with an example:"
      - echo "1. cd {{.EXAMPLES_DIR}}/<example-name>"
      - echo "2. Read the README.md for detailed instructions"
      - echo "3. Run the tasks"
      - echo ""
      - echo "Visit https://tvangundy.github.io"

  default:
    cmds:
      - |
        echo ""
        echo "Namespace sensitive tasks"
        echo ""
        echo "    task <namespace>:help"
        echo ""
        echo "Available namespaces"
        echo ""
        echo "workspace, device, sops, docker, vhs, talos"
        echo ""
        echo "To run a task:"
        echo "    task <namespace>:<task>"
        echo ""
        echo "Example:"
        echo "    task sops:decrypt -- <file>"
        echo "    task device:list-disks"
        echo "    task docker:clean"
    silent: true

