# https://taskfile.dev

version: '3'

includes:
  workspace: ./tasks/workspace
  sops: ./tasks/sops
  device: ./tasks/device
  docker: tasks/docker
  vhs: tasks/vhs
  talos: tasks/talos
  incus: tasks/incus
  runner: tasks/runner
  dev: tasks/dev

tasks:
  help:
    silent: true
    desc: Workspace help
    cmds:
      - |
        echo "Workspace help"
        echo ""
        echo "    task help"
        echo ""

        # Open documentation site in browser
        if [[ "$(uname)" == "Darwin" ]]; then
          open https://tvangundy.github.io
        elif [[ "$(uname)" == "Linux" ]]; then
          xdg-open https://tvangundy.github.io 2>/dev/null || sensible-browser https://tvangundy.github.io 2>/dev/null || echo "Please open https://tvangundy.github.io in your browser"
        else
          echo "Please open https://tvangundy.github.io in your browser"
        fi
        
  default:
    cmds:
      - |
        echo ""
        echo "Quick access to documentation:"
        echo "    task help              
        echo ""
        echo "Namespace sensitive tasks"
        echo ""
        echo "    task <namespace>:help"
        echo ""
        echo "Available namespaces"
        echo ""
        echo "workspace, device, sops, docker, vhs, talos, incus, runner, dev"
        echo ""
        echo "To run a task:"
        echo "    task <namespace>:<task>"
        echo ""
        echo "Example:"
        echo "    task sops:decrypt -- <file>"
        echo "    task device:list-disks"
        echo "    task docker:clean"
    silent: true

