---
version: "3"

vars:
  CONTEXTS_ROOT: "{{.WINDSOR_PROJECT_ROOT}}/contexts"
  DEFAULT_AWS_PROFILE: "public"

  CONTEXT: 
    sh: windsor context get

  SECRETS_YAML: "{{.CONTEXTS_ROOT}}/{{.CONTEXT}}/secrets.yaml"
  ENC_SECRETS_YAML: "{{.CONTEXTS_ROOT}}/{{.CONTEXT}}/secrets.enc.yaml"

tasks:

  generate-secrets-file:
    desc: Generates a new secrets file for the current context
    cmds:
      - |
        mkdir -p {{.CONTEXTS_ROOT}}/{{.CONTEXT}}
        echo "TEST_ENV_VAR: value" > {{.SECRETS_YAML}}
        echo "Generated: {{.SECRETS_YAML}}"
    silent: true

  encrypt-secrets-file:
    desc: Encrypts the secrets file
    cmds:
      - |
        sops -e --output {{.ENC_SECRETS_YAML}} {{.SECRETS_YAML}}
    silent: true

  decrypt-secrets-file:
    desc: Decrypts the secrets file
    cmds:
      - |
        sops -d --output {{.SECRETS_YAML}} {{.ENC_SECRETS_YAML}}
    silent: true

  help:
    desc: "Prints this help message"
    cmds:
      - |
        echo ""
        echo " SOPS Operations"
        echo "  task sops:generate-secrets-file"
        echo "  task sops:encrypt-secrets-file"
        echo "  task sops:decrypt-secrets-file"
        echo ""
    silent: true

