version: '3'

tasks:
  default:
    cmds:
      - echo "Sidero Omni Setup (Coming Soon)"
      - echo "This example is under development. Check back later for implementation details."

  setup:
    cmds:
      - echo "Setup task coming soon"

  run:
    cmds:
      - echo "Run task coming soon"

  test:
    cmds:
      - echo "Test task coming soon"

  clean:
    cmds:
      - echo "Clean task coming soon" 
