---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: home-assistant
      # renovate: datasource=helm depName=home-assistant package=home-assistant helmRepo=https://small-hack.github.io/home-assistant-chart/
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: home-assistant
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant

    # Use default ClusterIP service
    service:
      type: ClusterIP
      port: 8123
    
    # Enable ingress
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      hosts:
        - host: home-assistant.test
          paths:
            - path: /
              pathType: Prefix
    
    # Enable persistent storage
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: "single"
    
    # Lower resource requirements to help with scheduling
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    
    # Home Assistant specific configuration
    homeAssistant:
      configuration: |
        # Loads default set of integrations. Do not remove.
        default_config:

        # Enable HTTP settings for reverse proxy
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16

        # Load frontend themes from the themes folder
        frontend:
          themes: !include_dir_merge_named themes

        automation: !include automations.yaml
        script: !include scripts.yaml
        scene: !include scenes.yaml

    # Increase startup time to avoid readiness probe failures
    probes:
      startup:
        enabled: true
        spec:
          failureThreshold: 30
          periodSeconds: 10
          httpGet:
            path: /
            port: 8123

      liveness:
        enabled: true
        spec:
          failureThreshold: 3
          initialDelaySeconds: 60
          httpGet:
            path: /
            port: 8123
      
      readiness:
        enabled: true
        spec:
          failureThreshold: 3
          initialDelaySeconds: 60
          httpGet:
            path: /
            port: 8123
