# https://taskfile.dev

version: '3'

includes:
  docker: ../../tasks/docker.yaml

tasks:

  default:
    cmds:
      - echo "windsor init local"
      - echo "windsor up --install --verbose"
      - echo "kubectl port-forward --address 0.0.0.0 svc/home-assistant -n home-assistant 8123:8123 &"
    silent: true
